OnlineStore/OnlineStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('about/', include('about.urls')),
    path('checkout/', include('checkout.urls')),
    path('users/', include('users.urls')),
    path('', include('store.urls')),
    path('', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

OnlineStore/cart/urls.py
from django.urls import path

from .views import add_to_cart, cart, delete_cart_item, update_cart_item

app_name = 'cart'

urlpatterns = [
    path('', cart, name='cart'),
    path('add/<slug:item_slug>/', add_to_cart, name='add_to_cart'),
    path('delete/<slug:item_slug>/', delete_cart_item, name='delete_cart_item'),
    path('update_cart_item/', update_cart_item, name='update_cart_item'),
]

OnlineStore/users/urls.py
from django.contrib.auth.views import (LoginView, LogoutView,
                                       PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import path, reverse_lazy

from .views import SignUp, feedback_processing, profile, user_orders

app_name = 'users'

urlpatterns = [
    path('orders/', user_orders, name='user_orders'),
    path('profile/', profile, name='profile'),
    path('feedback-processing/', feedback_processing, name='feedback_processing'),
    path(
        'auth/logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),

    path('auth/signup/', SignUp.as_view(), name='signup'),

    path(
        'auth/login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),

    path(
        'auth/password_reset/',
        PasswordResetView.as_view(
            template_name='users/managment/password_reset_form.html',
            email_template_name='users/managment/password_reset_email.html',
            success_url='done/'),
        name='password_reset_form'
    ),

    path('auth/password_reset/done/',
         PasswordResetDoneView.as_view(
             template_name='users/managment/password_reset_done.html'),
         name='password_reset_done'),

    path('auth/reset/done/',
         PasswordResetCompleteView.as_view(
             template_name='users/managment/reset_done.html'),
         name='reset_done'),

    path('auth/password_reset_confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='users/managment/password_reset_confirm.html',
             success_url=reverse_lazy('users:reset_done')),
         name='password_reset_confirm'),

    path(
        'auth/password_reset_complete/',
        PasswordResetCompleteView.as_view(
            template_name='users/managment/password_reset_complete.html'),
        name='password_reset_complete'
    ),

    path(
        'auth/password_change/',
        PasswordChangeView.as_view(
            template_name='users/managment/password_change_form.html',
            success_url='done/'),
        name='password_change'
    ),
    path(
        'auth/password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/managment/password_change_done.html'),
        name='password_change_done'
    ),
]

OnlineStore/users/models.py
from django.db import models


class Feedback(models.Model):
    feedback_name = models.CharField(max_length=50, verbose_name='Имя покупателя',)
    feedback_email = models.EmailField(verbose_name='Почта покупателя',)
    feedback_message = models.TextField(verbose_name='Текст',)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания',)

    class Meta:
        verbose_name = 'Обратная связь покупателя'
        verbose_name_plural = 'Обратная связь покупателя'

    def __str__(self):
        return self.feedback_message[:30]

OnlineStore/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from .models import Feedback

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedback_name', 'feedback_email', 'feedback_message']

OnlineStore/users/views.py
import asyncio

import telegram
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from OnlineStore.settings import TELEGRAM_CHAT_ID, TELEGRAM_TOKEN
from checkout.models import Order
from .forms import CreationForm, FeedbackForm
from .models import Feedback


@login_required
def user_orders(request):
    """
    Представление списка заказов пользователя.
    """
    orders = Order.objects.filter(user=request.user)
    context = {
        'orders': orders,
    }
    return render(request, 'users/user_orders.html', context)


@login_required
def profile(request):
    """
    Представление профиля пользователя.
    """
    return render(request, 'users/profile.html')


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('store:home')
    template_name = 'users/signup.html'


async def send_telegram_message(message):
    """
    Асинхронная функция для отправки сообщения в ТГ.
    """
    bot = telegram.Bot(token=TELEGRAM_TOKEN)
    chat_id = TELEGRAM_CHAT_ID
    await bot.send_message(chat_id=chat_id, text=message)


def feedback_processing(request):
    """
    Представление приема и обработки для обратной связи.
    """
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            feedback = Feedback(
                feedback_name=form.cleaned_data['feedback_name'],
                feedback_email=form.cleaned_data['feedback_email'],
                feedback_message=form.cleaned_data['feedback_message'],
            )
            feedback.save()

            # Отпрака сообщения
            message = f"Новое сообщение от {feedback.feedback_name} ({feedback.feedback_email}): {feedback.feedback_message}"
            asyncio.run(send_telegram_message(message))

            return render(request, 'users/feedback_success.html')
    return render(request, 'users/feedback_failed.html')

OnlineStore/templates/users/managment/password_change_done.html
{% extends "base.html" %}

{% block content %}
<h1>Пароль изменен</h1>
<p>Ваш пароль был успешно изменен.</p>
{% endblock %}

OnlineStore/templates/users/managment/password_change_form.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
{% endblock %}

{% block content %}
<h1>Смена пароля</h1>
<p>Заполните форму для смены пароля.</p>
<form method="POST" action="{% url 'users:password_change' %}">
{% csrf_token %}
{% for field in form %}
<p>
<div class="form-field">
  <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
</div>
{% if form.errors %}
  <div class="alert alert-danger">
  {% for error in field.errors %}
    <p>{{ error }}</p>
  {% endfor %}
  </div>
{% endif %}
</p>
{% endfor %}
<input type="submit" value="Сменить пароль">
</form>
{% endblock %}

OnlineStore/templates/users/managment/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<h1>Пароль изменен успешно!</h1>
<p>Установлен новый пароль. Вы можете <a href="{% url 'users:login' %}">войти</a>.</p>
{% endblock %}

OnlineStore/templates/users/managment/password_reset_confirm.html
{% extends "base.html" %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
{% endblock %}

{% block content %}
{% if validlink %}
  <h1>Установите новый пароль</h1>
  <form method="POST" >
    {% csrf_token %}
    {% for field in form %}
    <p>
    <div class="form-field">
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for error in field.errors %}
          <p>{{ error }}</p>
        {% endfor %}
    </div>
  {% endif %}
  </p>
  {% endfor %}
    <input type="submit" value="Установить">
  </form>
{% else %}
  <p>Ссылка измененения пароля недействительна, скорее всего она уже была использована. Пожалуйста, запросите смену пароля еще раз.</p>
{% endif %}
{% endblock %}

OnlineStore/templates/users/managment/password_reset_done.html
{% extends "base.html" %}

{% block content %}
<h1>Отправлено письмо</h1>
<p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля.</p>
{% endblock %}

OnlineStore/templates/users/managment/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow thelink below:
{{ protocol }}://{{ domain }}{% url "users:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

OnlineStore/templates/users/managment/password_reset_form.html
{% extends 'base.html' %}

{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static "assets/css/users.css"%}" />
{% endblock %}

{% block content %}
  <h1>Забыли пароль?</h1>
  <p>Введите почту в форму и мы вышлем Вам на нее инстуркцию по смене пароля.</p>

  <form method="POST" action="{% url 'users:password_reset_form' %}">
    {% csrf_token %}
    {% for field in form %}
    <p>
    <div class="form-field">
      <label for="{{ field.id_for_label }}">{{ field.label }}:</label> {{ field }}
    </div>
    {% if form.errors %}
    <div class="alert alert-danger">
        {% for error in field.errors %}
          <p>{{ error }}</p>
        {% endfor %}
    </div>
  {% endif %}
  </p>
  {% endfor %}
    <input type="submit" value="Отправить">
  </form>
{% endblock %}

OnlineStore/templates/users/managment/reset_done.html
{% extends "base.html" %}

{% block content %}
<h1>Восстановление пароля завершено</h1>
<p>Ваш пароль был сохранен. Теперь вы можете войти.</p>
<p><a href="{% url 'users:login' %}">Войти</a></p>
{% endblock %}